### ISSUE TITLE
Adresse I2C

### ISSUE THREAD

**Issue by fab-uleuh** [Kampi/RV-3028-C7#2]
Hello

I try to use your lib with Zephyr.

Adresse I2C for RV-3028-C7 is A4h and A5h for read and write 
So why did you put  #define RV3028_ADDRESS                      0x52

Thank you ! 
Thanks for you work !

**Comment by Kampi** [comment]
Hi,
both are correct. `0xA4` is the shifted address `0x52`. The nRF SDK expects in the driver function `nrf_drv_twi_tx` as `address` only 7 LSB of the address because the driver will shift the address by one position and apply the R/W bit. 
Please take a look at the [documentation](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v14.0.0%2Fgroup__nrf__drv__twi.html)

Does Zephyr use a specific preprocessor macro to indicate a build for Zephyr OS? If so the macro can be used to differentiate between both.
